namespace Propostas.Infra.Data.Seeds
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Propostas.Domain.Models;
    using Propostas.Infra.Data.Context;

    public class PaisInitializer
    {
        private PropostasContext context;
        private ICollection<Pais> paises;

        public PaisInitializer(PropostasContext context)
        {
            this.context = context;
        }

        public async Task Seed()
        {
            this.paises = this.GeneratePaises();
            var paisesIncluidos = this.context.Paises.ToList();

            foreach (var pais in this.paises)
            {
                if (!paisesIncluidos.Any(c => c.CodigoBacen == pais.CodigoBacen))
                {
                    this.context.Add(pais);
                }
            }

            await this.context.SaveChangesAsync();
        }

        private ICollection<Pais> GeneratePaises()
        {
            var paises = new List<Pais>
            {
                new Pais("0132", "Afeganistão", false, null),
                new Pais("7560", "África do Sul", false, null),
                new Pais("0175", "Albânia, República da", false, null),
                new Pais("0230", "Alemanha", false, null),
                new Pais("0370", "Andorra", true, null),
                new Pais("0400", "Angola", false, null),
                new Pais("0418", "Anguilla", true, null),
                new Pais("0434", "Antigua e Barbuda", true, null),
                new Pais("0477", "Antilhas Holandesas", true, null),
                new Pais("0531", "Arábia Saudita", false, null),
                new Pais("0590", "Argélia", false, null),
                new Pais("0639", "Argentina", false, null),
                new Pais("0647", "Armênia, República da", false, null),
                new Pais("0655", "Aruba", false, null),
                new Pais("0698", "Austrália", false, null),
                new Pais("0728", "Áustria", false, null),
                new Pais("0736", "Azerbaijão, República do", false, null),
                new Pais("0779", "Bahamas, Ilhas", true, null),
                new Pais("0809", "Bahrein, Ilhas", true, null),
                new Pais("0817", "Bangladesh", false, null),
                new Pais("0833", "Barbados", true, null),
                new Pais("0850", "Belarus", false, null),
                new Pais("0876", "Bélgica", false, null),
                new Pais("0884", "Belize", true, null),
                new Pais("2291", "Benin", false, null),
                new Pais("0906", "Bermudas", true, null),
                new Pais("0973", "Bolívia", false, null),
                new Pais("0981", "Bósnia-Herzegovina", false, null),
                new Pais("1015", "Botsuana", false, null),
                new Pais("1058", "Brasil", false, "BRA"),
                new Pais("1082", "Brunei", false, null),
                new Pais("1112", "Bulgária, República da", false, null),
                new Pais("0310", "Burkina Faso", false, null),
                new Pais("1155", "Burundi", false, null),
                new Pais("1198", "Butão", false, null),
                new Pais("1279", "Cabo Verde, República de", false, null),
                new Pais("1457", "Camarões", false, null),
                new Pais("1414", "Camboja", false, null),
                new Pais("1490", "Canadá", false, "CAN"),
                new Pais("1504", "Canal, Ilhas do (Jersey e Guernsey)", true, null),
                new Pais("1511", "Canárias, Ilhas", false, null),
                new Pais("1546", "Catar", false, null),
                new Pais("1376", "Cayman, Ilhas", true, null),
                new Pais("1538", "Cazaquistão, República do", false, null),
                new Pais("7889", "Chade", false, null),
                new Pais("1589", "Chile", false, null),
                new Pais("1600", "China, República Popular da", false, null),
                new Pais("1635", "Chipre", true, null),
                new Pais("5118", "Christmas, Ilha (Navidad)", false, null),
                new Pais("7412", "Cingapura", false, null),
                new Pais("1651", "Cocos (Keeling), Ilhas", false, null),
                new Pais("1694", "Colômbia", false, null),
                new Pais("1732", "Comores, Ilhas", false, null),
                new Pais("8885", "Congo, República Democrática do", false, null),
                new Pais("1775", "Congo, República do", false, null),
                new Pais("1830", "Cook, Ilhas", true, null),
                new Pais("1872", "Coréia, Rep. Pop. Democrática da", false, null),
                new Pais("1902", "Coréia, República da", false, null),
                new Pais("1937", "Costa do Marfim", false, null),
                new Pais("1961", "Costa Rica", true, null),
                new Pais("1988", "Coveite", false, null),
                new Pais("1953", "Croácia, República da", false, null),
                new Pais("1996", "Cuba", false, null),
                new Pais("2321", "Dinamarca", false, null),
                new Pais("7838", "Djibuti", true, null),
                new Pais("2356", "Dominica, Ilha", true, null),
                new Pais("2402", "Egito", false, null),
                new Pais("6874", "El Salvador", false, null),
                new Pais("2445", "Emirados Árabes Unidos", false, null),
                new Pais("2399", "Equador", false, null),
                new Pais("2437", "Eritréia", false, null),
                new Pais("6289", "Escócia", false, null),
                new Pais("2470", "Eslovaca, República", false, null),
                new Pais("2461", "Eslovênia, República da", false, null),
                new Pais("2453", "Espanha", false, null),
                new Pais("2496", "Estados Unidos", false, "EUA"),
                new Pais("2518", "Estônia, República da", false, null),
                new Pais("2534", "Etiópia", false, null),
                new Pais("2550", "Falkland (Ilhas Malvinas)", false, null),
                new Pais("2593", "Feroe, Ilhas", false, null),
                new Pais("8702", "Fiji", false, null),
                new Pais("2674", "Filipinas", false, null),
                new Pais("2712", "Finlândia", false, null),
                new Pais("1619", "Formosa (Taiwan)", false, null),
                new Pais("2755", "França", false, null),
                new Pais("2810", "Gabão", false, null),
                new Pais("6289", "Gales, País de", false, null),
                new Pais("2852", "Gâmbia", false, null),
                new Pais("2895", "Gana", false, null),
                new Pais("2917", "Geórgia, República da", false, null),
                new Pais("2933", "Gibraltar", true, null),
                new Pais("6289", "Grã-Bretanha", false, null),
                new Pais("2976", "Granada", true, null),
                new Pais("3018", "Grécia", false, null),
                new Pais("3050", "Groenlândia", false, null),
                new Pais("3093", "Guadalupe", false, null),
                new Pais("3131", "Guam", false, null),
                new Pais("3174", "Guatemala", false, null),
                new Pais("3379", "Guiana", false, null),
                new Pais("3255", "Guiana Francesa", false, null),
                new Pais("3298", "Guiné", false, null),
                new Pais("3344", "Guiné-Bissau", false, null),
                new Pais("3310", "Guiné-Equatorial", false, null),
                new Pais("3417", "Haiti", false, null),
                new Pais("5738", "Holanda (Países Baixos)", false, null),
                new Pais("3450", "Honduras", false, null),
                new Pais("3514", "Hong Kong, Região Adm. Especial", false, null),
                new Pais("3557", "Hungria, República da", false, null),
                new Pais("3573", "Iêmen", false, null),
                new Pais("3611", "Índia", false, null),
                new Pais("3654", "Indonésia", false, null),
                new Pais("6289", "Inglaterra", false, null),
                new Pais("3727", "Irã, República Islâmica do", false, null),
                new Pais("3697", "Iraque", false, null),
                new Pais("3751", "Irlanda", false, null),
                new Pais("6289", "Irlanda do Norte", false, null),
                new Pais("3794", "Islândia", false, null),
                new Pais("3832", "Israel", false, null),
                new Pais("3867", "Itália", false, "ITA"),
                new Pais("3883", "Iugoslávia, República Fed. da", false, null),
                new Pais("3913", "Jamaica", false, null),
                new Pais("3999", "Japão", false, "JPN"),
                new Pais("3964", "Johnston, Ilhas", false, null),
                new Pais("4030", "Jordânia", false, null),
                new Pais("4111", "Kiribati", false, null),
                new Pais("4200", "Laos, Rep. Pop. Democrática do", false, null),
                new Pais("4235", "Lebuan", true, null),
                new Pais("4260", "Lesoto", false, null),
                new Pais("4278", "Letônia, República da", false, null),
                new Pais("4316", "Líbano", false, null),
                new Pais("4340", "Libéria", true, null),
                new Pais("4383", "Líbia", false, null),
                new Pais("4405", "Liechtenstein", true, null),
                new Pais("4421", "Lituânia, República da", false, null),
                new Pais("4456", "Luxemburgo", false, null),
                new Pais("4472", "Macau", false, null),
                new Pais("4499", "Macedônia", false, null),
                new Pais("4502", "Madagascar", false, null),
                new Pais("4525", "Madeira, Ilha da", true, null),
                new Pais("4553", "Malásia", false, null),
                new Pais("4588", "Malavi", false, null),
                new Pais("4618", "Maldivas", false, null),
                new Pais("4642", "Máli", false, null),
                new Pais("4677", "Malta", true, null),
                new Pais("3595", "Man, Ilhas", true, null),
                new Pais("4723", "Marianas do Norte", false, null),
                new Pais("4740", "Marrocos", false, null),
                new Pais("4766", "Marshall, Ilhas", true, null),
                new Pais("4774", "Martinica", false, null),
                new Pais("4855", "Maurício", true, null),
                new Pais("4880", "Mauritânia", false, null),
                new Pais("4936", "México", false, "MEX"),
                new Pais("0930", "Mianmar (Birmânia)", false, null),
                new Pais("4995", "Micronésia", false, null),
                new Pais("4901", "Midway, Ilhas", false, null),
                new Pais("5053", "Moçambique", false, null),
                new Pais("4944", "Moldávia, República da", false, null),
                new Pais("4952", "Mônaco", true, null),
                new Pais("4979", "Mongólia", false, null),
                new Pais("5010", "Montserrat, Ilhas", true, null),
                new Pais("5070", "Namíbia", false, null),
                new Pais("5088", "Nauru", true, null),
                new Pais("5177", "Nepal", false, null),
                new Pais("5215", "Nicarágua", false, null),
                new Pais("5258", "Niger", false, null),
                new Pais("5282", "Nigéria", false, null),
                new Pais("5312", "Niue, Ilha", true, null),
                new Pais("5355", "Norfolk, Ilha", false, null),
                new Pais("5380", "Noruega", false, null),
                new Pais("5428", "Nova Caledônia", false, null),
                new Pais("5487", "Nova Zelândia", false, null),
                new Pais("5568", "Omã", false, null),
                new Pais("5738", "Países Baixos (Holanda)", false, null),
                new Pais("5754", "Palau", false, null),
                new Pais("5800", "Panamá", true, null),
                new Pais("5452", "Papua Nova Guiné", false, null),
                new Pais("5762", "Paquistão", false, null),
                new Pais("5860", "Paraguai", false, null),
                new Pais("5894", "Peru", false, null),
                new Pais("5932", "Pitcairn, Ilha", false, null),
                new Pais("5991", "Polinésia Francesa", false, null),
                new Pais("6033", "Polônia, República da", false, null),
                new Pais("6114", "Porto Rico", false, null),
                new Pais("6076", "Portugal", false, null),
                new Pais("6238", "Quênia", false, null),
                new Pais("6254", "Quirguiz, República", false, null),
                new Pais("6289", "Reino Unido", false, null),
                new Pais("6408", "República Centro-Africana", false, null),
                new Pais("6475", "República Dominicana", false, null),
                new Pais("6602", "Reunião, Ilha", false, null),
                new Pais("6700", "Romênia", false, null),
                new Pais("6750", "Ruanda", false, null),
                new Pais("6769", "Rússia", false, null),
                new Pais("6858", "Saara Ocidental", false, null),
                new Pais("6777", "Salomão, Ilhas", false, null),
                new Pais("6904", "Samoa", true, null),
                new Pais("6912", "Samoa Americana", false, null),
                new Pais("6971", "San Marino", true, null),
                new Pais("7102", "Santa Helena", false, null),
                new Pais("7153", "Santa Lúcia", true, null),
                new Pais("6955", "São Cristóvão e Neves", true, null),
                new Pais("7005", "São Pedro e Miquelon", false, null),
                new Pais("7200", "São Tomé e Príncipe, Ilhas", false, null),
                new Pais("7056", "São Vicente e Granadinas", true, null),
                new Pais("7285", "Senegal", false, null),
                new Pais("7358", "Serra Leoa", false, null),
                new Pais("7315", "Seychelles", true, null),
                new Pais("7447", "Síria, República Árabe da", false, null),
                new Pais("7480", "Somália", false, null),
                new Pais("7501", "Sri Lanka", false, null),
                new Pais("7544", "Suazilândia", false, null),
                new Pais("7595", "Sudão", false, null),
                new Pais("7641", "Suécia", false, null),
                new Pais("7676", "Suíça", false, null),
                new Pais("7706", "Suriname", false, null),
                new Pais("7722", "Tadjiquistão", false, null),
                new Pais("7765", "Tailândia", false, null),
                new Pais("7803", "Tanzânia, República Unida da", false, null),
                new Pais("7919", "Tcheca, República", false, null),
                new Pais("7820", "Território Britânico Oc. Índico", false, null),
                new Pais("7951", "Timor Leste", false, null),
                new Pais("8001", "Togo", false, null),
                new Pais("8109", "Tonga", true, null),
                new Pais("8052", "Toquelau, Ilhas", false, null),
                new Pais("8150", "Trinidad e Tobago", false, null),
                new Pais("8206", "Tunísia", false, null),
                new Pais("8230", "Turcas e Caicos, Ilhas", true, null),
                new Pais("8249", "Turcomenistão, República do", false, null),
                new Pais("8273", "Turquia", false, null),
                new Pais("8281", "Tuvalu", false, null),
                new Pais("8311", "Ucrânia", false, null),
                new Pais("8338", "Uganda", false, null),
                new Pais("8451", "Uruguai", false, null),
                new Pais("8478", "Uzbequistão, República do", false, null),
                new Pais("5517", "Vanuatu", true, null),
                new Pais("8486", "Vaticano, Estado da Cidade do", false, null),
                new Pais("8508", "Venezuela", false, null),
                new Pais("8583", "Vietnã", false, null),
                new Pais("8630", "Virgens, Ilhas (Britânicas)", true, null),
                new Pais("8664", "Virgens, Ilhas (E.U.A.)", true, null),
                new Pais("8737", "Wake, Ilha", false, null),
                new Pais("8753", "Wallis e Futuna, Ilhas", false, null),
                new Pais("8907", "Zâmbia", false, null),
                new Pais("6653", "Zimbábue", false, null),
                new Pais("8958", "Zona do Canal do Panamá", false, null)
            };

            return paises;
        }
    }
}
